### ISSUE TITLE
lhusova skuska

### ISSUE THREAD

**Issue by mvala** [upjs-jf/psdjf#11]
Convert ALICE data to Psd Format and draw Px, Py, Px vs. Py and Pt

**Comment by lhusova** [comment]
I`ve already pushed the needed macros. They are in file marocs/ALICE.

**Comment by mvala** [comment]
Ok. Got it. I will try to do it today or tomorrow

**Comment by lhusova** [comment]
How can I do the library libpsdjf.so?

**Comment by mvala** [comment]
I had some problems with par so simpli link PsdEvent.h,cxx and PsdTrack.h,cxx to local directory for now

**Comment by lhusova** [comment]
I've already done it

**Comment by lhusova** [comment]
But I receve these two erroers:
Error in <TUnixSystem::FindDynamicLibrary>: libpsdjf.so does not exist in .:/usr/lib64/root:
Error in <TSelector::GetSelector>: The file PsdAnalysisSelector.cxx+ does not define a class named PsdAnalysisSelector.

**Comment by mvala** [comment]
show me your directory structure in macros/ALICE. Also please try to remove add .d and .so and .pcm

**Comment by lhusova** [comment]
I pushed all. And the errors I receaved by turn m06.C

**Comment by mvala** [comment]
Write the error message.

**Comment by lhusova** [comment]
Error in <TSelector::GetSelector>: The file PsdAnalysisSelector.cxx+ does not define a class named PsdAnalysisSelector.

**Comment by lhusova** [comment]
I still receave this error, but I think unless thi my task is done. Please check it.

**Comment by mvala** [comment]
Traveling to cern. I will have a look as soon as posible

**Comment by mvala** [comment]
I am running
```
root 'runAnalysis.C("local","full")'
```
and i don't get any error. If you have error please write it here.

**Comment by mvala** [comment]
I see in your task
```
     PsdTrack *t = new PsdTrack();
     t->SetPx(lPx);
     t->SetPx(lPy);
     t->SetPx(lPz);
```

**Comment by mvala** [comment]
You should not create new PsdTrack. You should
```
PsdTrack *t = AddTrack();
 t->SetPx(lPx);
 t->SetPx(lPy);
 t->SetPx(lPz);
```

**Comment by lhusova** [comment]
I fixed the PsdTrack but I have this error by runAnalysis.C : 
'AddTrack' was not declared in this scope
      PsdTrack *t = AddTrack();

and by m06.C this error: 

error: /home/lhusova/git/psdjf/macros/./PsdAnalysisSelector_cxx.so: undefined symbol: _ZTI8PsdEvent
Load Error: Failed to load Dynamic link library /home/lhusova/git/psdjf/macros/./PsdAnalysisSelector_cxx.so
Error in <TSelector::GetSelector>: The file PsdAnalysisSelector.cxx+ does not define a class named PsdAnalysisSelector.

**Comment by mvala** [comment]
Sorry it should be
```
fOutEvent->AddTrack()
```

**Comment by mvala** [comment]
And for this error. That means that i cannot find PsdEvent class. Did you load libpsdjf.so? Did you source ```
scripts/env.sh
```

**Comment by lhusova** [comment]
Yes I sourced the scripts/env.sh, but I still have the error.

And the PsdTrack should be ok now.

**Comment by mvala** [comment]
Ok. Please send me all your commands which you did and alos output so i see error

**Comment by lhusova** [comment]
[lhusova@localhost ~]$ cd git/psdjf/macros/
[lhusova@localhost macros]$ source ../scripts/env.sh 
[lhusova@localhost macros]$ root m06.C 
   ------------------------------------------------------------
  | Welcome to ROOT 6.08/02                http://root.cern.ch |
  |                               (c) 1995-2016, The ROOT Team |
  | Built for linuxx8664gcc                                    |
  | From tag v6-08-02, 2 December 2016                         |
  | Try '.help', '.demo', '.license', '.credits', '.quit'/'.q' |
   ------------------------------------------------------------

root [0] 
Processing m06.C...
cling::DynamicLibraryManager::loadLibrary(): libCint.so: cannot open shared object file: No such file or directory
Warning in <TClass::Init>: no dictionary for class PsdEvent is available
Warning in <TClass::Init>: no dictionary for class PsdTrack is available
cling::DynamicLibraryManager::loadLibrary(): /home/lhusova/git/psdjf/macros/PsdAnalysisSelector_cxx.so: undefined symbol: _ZTI8PsdEvent
Error in <TSelector::GetSelector>: The file PsdAnalysisSelector.cxx+ does not define a class named PsdAnalysisSelector.
root [1]

**Comment by mvala** [comment]
Where is your root from?

**Comment by lhusova** [comment]
I thing from the system.

**Comment by mvala** [comment]
Show me 
```
rpm -qa| grep root-
```

**Comment by lhusova** [comment]
root-graf-gpad-6.08.02-1.fc24.x86_64
root-hist-painter-6.08.02-1.fc24.x86_64
root-xproof-6.08.02-1.fc24.x86_64
root-cling-6.08.02-1.fc24.x86_64
root-graf-x11-6.08.02-1.fc24.x86_64
root-graf3d-gl-6.08.02-1.fc24.x86_64
root-net-6.08.02-1.fc24.x86_64
root-graf-asimage-6.08.02-1.fc24.x86_64
root-netx-6.08.02-1.fc24.x86_64
root-matrix-6.08.02-1.fc24.x86_64
root-mathcore-6.08.02-1.fc24.x86_64
root-proof-6.08.02-1.fc24.x86_64
root-proofd-6.08.02-1.fc24.x86_64
alice-root-5.34.36-0-0.fc24.x86_64
root-fonts-6.08.02-1.fc24.noarch
root-graf-6.08.02-1.fc24.x86_64
root-core-6.08.02-1.fc24.x86_64
root-geom-6.08.02-1.fc24.x86_64
alice-aliroot-v5.08.16.rc3-0-0.fc24.x86_64
root-multiproc-6.08.02-1.fc24.x86_64
root-hist-6.08.02-1.fc24.x86_64
root-gui-6.08.02-1.fc24.x86_64
root-io-6.08.02-1.fc24.x86_64
root-physics-6.08.02-1.fc24.x86_64
root-minuit-6.08.02-1.fc24.x86_64
root-net-rpdutils-6.08.02-1.fc24.x86_64
root-proof-sessionviewer-6.08.02-1.fc24.x86_64
root-icons-6.08.02-1.fc24.noarch
root-tree-player-6.08.02-1.fc24.x86_64
root-6.08.02-1.fc24.x86_64
root-tree-6.08.02-1.fc24.x86_64
root-gui-ged-6.08.02-1.fc24.x86_64
root-graf-postscript-6.08.02-1.fc24.x86_64
root-graf3d-6.08.02-1.fc24.x86_64

**Comment by mvala** [comment]
i see 2 root version root from system and aliroot (with root). This can be problem. Please use root from aliroot and it should be fixed

**Comment by lhusova** [comment]
and how can I choose, which version I want to use?

**Comment by mvala** [comment]
```aliroot-version``` will show you available aliroot
```
aliroot-version set <aliphysis-version>
```
then logout and login

**Comment by mvala** [comment]
Let's have ezuce meeting and we can solve it online
